title: Jaehyuk Lee
description: Jaehyuk Lee's blog for data analyst
author: Jaehyuk Lee
avatar: /KakaoTalk_20210511_001014942.jpg
email: jaykees@khu.ac.kr

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: KakaoTalk_20210511_001014942.jpg
skin: daylight.scss
description: 안녕하세요
social:
  name: Jaehyuk Lee
  links:
    - https://github.com/lee0429sK
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
